### ISSUE TITLE
wrong type on nuke.execute

### ISSUE THREAD

**Issue by mruegenberg** [sisoe24/nuke-python-stubs#3]
Hello,
thanks for this very useful package!

My editor was complaining about calling `nuke.execute` with a `Node` as the first argument - I think the type definition for nuke.execute should start with `def execute(nameOrNode: Union[str,Node]`

**Comment by sisoe24** [comment]
Hey! Thank you for letting me know!

You are right; it should be `Union[str, Node]`. I will fix it as soon as possible with the other errors I found. 

There are many instances where the parser cannot understand what's happening, so you likely find other mismatches. I usually "go to definition"  and manually adjust them to make the LSP happy.

Edit: 

You found even a bigger fish. Apparently, `execute` has an overloaded version that is being overwritten.

**Comment by sisoe24** [comment]
Ok! I made a bunch of fixes, including the various `execute` functions with its overloaded version. If you use visual studio code NukeTools, refresh the packages cache (command palette) `Nuke: Clear package cache` and add the stubs again `Nuke: Add python stubs`. Otherwise, you can find the updated versions in the latest [release](https://github.com/sisoe24/nuke-python-stubs/releases/tag/v0.3.1). Feel free to open an issue again if there is something wrong.
